name: Ruby

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1.81.0
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Building website
        run: bundle exec jekyll build

      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "_site"
          target: "groups/networking/www/426"
