name: Ruby

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.81.0

      - name: Building website
        run: |
          bundle install
          bundle exec jekyll build

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "_site"
          target: "groups/networking/www/426"
